import { FormSection } from "./types";

export const formSections: FormSection[] = [
  {
    id: "personal-info",
    title: "Personal Information",
    questions: [
      { id: "fullName", label: "Full Name", type: "text", required: true },
      { id: "age", label: "Age", type: "number", required: true, min: 1, max: 120 },
      { id: "height", label: "Height (cm)", type: "number", required: true, min: 50, max: 250 },
      { id: "weight", label: "Weight (kg)", type: "number", required: true, min: 20, max: 300 },
      { id: "occupation", label: "Occupation", type: "text", required: true },
    ],
  },
  {
    id: "primary-concern",
    title: "Primary Concern",
    questions: [
      {
        id: "mainConcern",
        label: "What brings you here today?",
        type: "multi-select",
        required: true,
        options: [
          { label: "Neck Pain", value: "neck-pain" },
          { label: "Upper Back Pain", value: "upper-back-pain" },
          { label: "Mid Back Pain", value: "mid-back-pain" },
          { label: "Lower Back Pain", value: "lower-back-pain" },
          { label: "Shoulder Pain", value: "shoulder-pain" },
          { label: "Hip Pain", value: "hip-pain" },
          { label: "Knee Pain", value: "knee-pain" },
          { label: "Poor Posture", value: "poor-posture" },
          { label: "Rounded Shoulders", value: "rounded-shoulders" },
          { label: "Forward Head Posture", value: "forward-head-posture" },
          { label: "Scoliosis", value: "scoliosis" },
          { label: "General Stiffness", value: "general-stiffness" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "primaryGoal",
        label: "What is your primary goal?",
        type: "single-select",
        required: true,
        options: [
          { label: "Improve Posture", value: "improve-posture" },
          { label: "Reduce Pain", value: "reduce-pain" },
          { label: "Improve Flexibility", value: "improve-flexibility" },
          { label: "Stand Taller", value: "stand-taller" },
          { label: "Improve Movement", value: "improve-movement" },
          { label: "Improve Confidence", value: "improve-confidence" },
          { label: "Improve Athletic Performance", value: "improve-athletic-performance" },
          { label: "Recover from Injury", value: "recover-from-injury" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "briefDescription",
        label: "Briefly describe what you'd like help with",
        type: "textarea",
        placeholder: "Tell us in your own words...",
      },
    ],
  },
  {
    id: "pain-assessment",
    title: "Pain Assessment",
    questions: [
      {
        id: "currentlyInPain",
        label: "Are you currently experiencing pain?",
        type: "single-select",
        required: true,
        options: [
          { label: "No", value: "no" },
          { label: "Occasionally", value: "occasionally" },
          { label: "Yes", value: "yes" },
        ],
      },
      {
        id: "painLocation",
        label: "Where do you feel discomfort or pain?",
        type: "multi-select",
        options: [
          { label: "Neck", value: "neck" },
          { label: "Upper Back", value: "upper-back" },
          { label: "Mid Back", value: "mid-back" },
          { label: "Lower Back", value: "lower-back" },
          { label: "Shoulders", value: "shoulders" },
          { label: "Chest", value: "chest" },
          { label: "Hips", value: "hips" },
          { label: "Knees", value: "knees" },
          { label: "Ankles", value: "ankles" },
          { label: "Feet", value: "feet" },
          { label: "Arms", value: "arms" },
          { label: "Hands", value: "hands" },
          { label: "Other", value: "other" },
        ],
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
      {
        id: "painSide",
        label: "Which side is affected?",
        type: "single-select",
        options: [
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
          { label: "Both", value: "both" },
          { label: "Centre", value: "centre" },
        ],
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
      {
        id: "painDuration",
        label: "How long have you had this discomfort or pain?",
        type: "single-select",
        options: [
          { label: "Less than 1 week", value: "less-than-1-week" },
          { label: "1–4 weeks", value: "1-4-weeks" },
          { label: "1–3 months", value: "1-3-months" },
          { label: "3–6 months", value: "3-6-months" },
          { label: "6–12 months", value: "6-12-months" },
          { label: "More than 1 year", value: "more-than-1-year" },
        ],
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
      {
        id: "painSeverity",
        label: "How severe is your pain today?",
        type: "slider",
        min: 0,
        max: 10,
        step: 1,
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
      {
        id: "painDescription",
        label: "How would you describe your pain?",
        type: "multi-select",
        options: [
          { label: "Sharp", value: "sharp" },
          { label: "Dull", value: "dull" },
          { label: "Aching", value: "aching" },
          { label: "Tightness", value: "tightness" },
          { label: "Burning", value: "burning" },
          { label: "Stiffness", value: "stiffness" },
          { label: "Tingling", value: "tingling" },
          { label: "Numbness", value: "numbness" },
          { label: "Throbbing", value: "throbbing" },
        ],
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
      {
        id: "painWorse",
        label: "What usually makes your pain worse?",
        type: "multi-select",
        options: [
          { label: "Sitting", value: "sitting" },
          { label: "Standing", value: "standing" },
          { label: "Walking", value: "walking" },
          { label: "Sleeping", value: "sleeping" },
          { label: "Computer Work", value: "computer-work" },
          { label: "Phone Use", value: "phone-use" },
          { label: "Lifting", value: "lifting" },
          { label: "Exercise", value: "exercise" },
          { label: "Driving", value: "driving" },
          { label: "Other", value: "other" },
        ],
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
      {
        id: "painRelief",
        label: "What usually relieves your pain?",
        type: "multi-select",
        options: [
          { label: "Rest", value: "rest" },
          { label: "Stretching", value: "stretching" },
          { label: "Walking", value: "walking" },
          { label: "Exercise", value: "exercise" },
          { label: "Heat", value: "heat" },
          { label: "Ice", value: "ice" },
          { label: "Massage", value: "massage" },
          { label: "Medication", value: "medication" },
          { label: "Nothing", value: "nothing" },
          { label: "Other", value: "other" },
        ],
        dependsOn: { questionId: "currentlyInPain", value: ["occasionally", "yes"] },
      },
    ],
  },
  {
    id: "injury-history",
    title: "Injury & Medical History",
    questions: [
      {
        id: "significantInjury",
        label: "Have you ever had a significant injury?",
        type: "single-select",
        required: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "injuryLocation",
        label: "Where was the injury?",
        type: "text",
        placeholder: "e.g. Lower back, left knee...",
        dependsOn: { questionId: "significantInjury", value: "yes" },
      },
      {
        id: "injuryWhen",
        label: "Approximately when did it occur?",
        type: "text",
        placeholder: "e.g. 6 months ago, 2022, Childhood",
        dependsOn: { questionId: "significantInjury", value: "yes" },
      },
      {
        id: "hadSurgery",
        label: "Have you ever had surgery involving your muscles, joints, or spine?",
        type: "single-select",
        required: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "diagnosedConditions",
        label: "Have you been diagnosed with any of the following?",
        type: "multi-select",
        options: [
          { label: "Scoliosis", value: "scoliosis" },
          { label: "Arthritis", value: "arthritis" },
          { label: "Herniated Disc", value: "herniated-disc" },
          { label: "Sciatica", value: "sciatica" },
          { label: "Osteoporosis", value: "osteoporosis" },
          { label: "None", value: "none" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "currentTreatment",
        label: "Are you currently receiving treatment?",
        type: "single-select",
        options: [
          { label: "Physiotherapy", value: "physiotherapy" },
          { label: "Chiropractic Care", value: "chiropractic" },
          { label: "Massage Therapy", value: "massage-therapy" },
          { label: "Medication", value: "medication" },
          { label: "None", value: "none" },
          { label: "Other", value: "other" },
        ],
      },
    ],
  },
  {
    id: "lifestyle",
    title: "Lifestyle",
    questions: [
      {
        id: "sittingHours",
        label: "How many hours do you sit each day?",
        type: "single-select",
        required: true,
        options: [
          { label: "Less than 2 hours", value: "less-than-2" },
          { label: "2–4 hours", value: "2-4" },
          { label: "4–6 hours", value: "4-6" },
          { label: "6–8 hours", value: "6-8" },
          { label: "More than 8 hours", value: "more-than-8" },
        ],
      },
      {
        id: "computerHours",
        label: "How many hours do you use a computer each day?",
        type: "single-select",
        required: true,
        options: [
          { label: "Less than 2 hours", value: "less-than-2" },
          { label: "2–4 hours", value: "2-4" },
          { label: "4–6 hours", value: "4-6" },
          { label: "6–8 hours", value: "6-8" },
          { label: "More than 8 hours", value: "more-than-8" },
        ],
      },
      {
        id: "phoneHours",
        label: "How many hours do you use your phone each day?",
        type: "single-select",
        required: true,
        options: [
          { label: "Less than 2 hours", value: "less-than-2" },
          { label: "2–4 hours", value: "2-4" },
          { label: "4–6 hours", value: "4-6" },
          { label: "6–8 hours", value: "6-8" },
          { label: "More than 8 hours", value: "more-than-8" },
        ],
      },
      {
        id: "morningPain",
        label: "Do you usually wake up with pain or stiffness?",
        type: "single-select",
        required: true,
        options: [
          { label: "Never", value: "never" },
          { label: "Sometimes", value: "sometimes" },
          { label: "Often", value: "often" },
          { label: "Every Day", value: "every-day" },
        ],
      },
    ],
  },
  {
    id: "physical-activity",
    title: "Physical Activity",
    questions: [
      {
        id: "currentlyExercise",
        label: "Do you currently exercise?",
        type: "single-select",
        required: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "exerciseDays",
        label: "How many days per week do you exercise?",
        type: "single-select",
        options: [
          { label: "0", value: "0" },
          { label: "1", value: "1" },
          { label: "2", value: "2" },
          { label: "3", value: "3" },
          { label: "4", value: "4" },
          { label: "5", value: "5" },
          { label: "6", value: "6" },
          { label: "7", value: "7" },
        ],
        dependsOn: { questionId: "currentlyExercise", value: "yes" },
      },
      {
        id: "exerciseType",
        label: "What type of exercise do you currently do?",
        type: "multi-select",
        options: [
          { label: "Gym", value: "gym" },
          { label: "Walking", value: "walking" },
          { label: "Running", value: "running" },
          { label: "Yoga", value: "yoga" },
          { label: "Pilates", value: "pilates" },
          { label: "Swimming", value: "swimming" },
          { label: "Cycling", value: "cycling" },
          { label: "Sports", value: "sports" },
          { label: "None", value: "none" },
          { label: "Other", value: "other" },
        ],
        dependsOn: { questionId: "currentlyExercise", value: "yes" },
      },
      {
        id: "stretchRegularly",
        label: "Do you stretch regularly?",
        type: "single-select",
        options: [
          { label: "Never", value: "never" },
          { label: "Occasionally", value: "occasionally" },
          { label: "Weekly", value: "weekly" },
          { label: "Daily", value: "daily" },
        ],
      },
    ],
  },
  {
    id: "goals-commitment",
    title: "Goals & Commitment",
    questions: [
      {
        id: "triedPostureCorrection",
        label: "Have you tried posture correction before?",
        type: "single-select",
        required: true,
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "whatTried",
        label: "What have you tried previously?",
        type: "multi-select",
        options: [
          { label: "Gym", value: "gym" },
          { label: "Stretching", value: "stretching" },
          { label: "Yoga", value: "yoga" },
          { label: "Physiotherapy", value: "physiotherapy" },
          { label: "Posture Brace", value: "posture-brace" },
          { label: "Massage Therapy", value: "massage-therapy" },
          { label: "Online Programmes", value: "online-programmes" },
          { label: "Other", value: "other" },
        ],
        dependsOn: { questionId: "triedPostureCorrection", value: "yes" },
      },
      {
        id: "biggestChallenge",
        label: "What was your biggest challenge?",
        type: "single-select",
        options: [
          { label: "Staying Consistent", value: "staying-consistent" },
          { label: "Didn't Know the Right Exercises", value: "didnt-know-exercises" },
          { label: "Didn't See Results", value: "didnt-see-results" },
          { label: "Pain Increased", value: "pain-increased" },
          { label: "Lack of Time", value: "lack-of-time" },
          { label: "Lost Motivation", value: "lost-motivation" },
          { label: "Other", value: "other" },
        ],
        dependsOn: { questionId: "triedPostureCorrection", value: "yes" },
      },
      {
        id: "successLookLike",
        label: "What would success look like for you?",
        type: "textarea",
        placeholder: "Describe your ideal outcome...",
      },
      {
        id: "hasDeadline",
        label: "Do you have a specific event or deadline you are working towards?",
        type: "single-select",
        options: [
          { label: "Yes", value: "yes" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "targetDate",
        label: "What is your target date?",
        type: "date",
        dependsOn: { questionId: "hasDeadline", value: "yes" },
      },
      {
        id: "dailyCommitment",
        label: "How much time can you realistically commit to posture exercises each day?",
        type: "single-select",
        options: [
          { label: "10 Minutes", value: "10" },
          { label: "15 Minutes", value: "15" },
          { label: "20 Minutes", value: "20" },
          { label: "30 Minutes", value: "30" },
          { label: "45 Minutes or More", value: "45+" },
        ],
      },
      {
        id: "bestTimeOfDay",
        label: "Which time of day works best for you?",
        type: "single-select",
        options: [
          { label: "Morning", value: "morning" },
          { label: "Afternoon", value: "afternoon" },
          { label: "Evening", value: "evening" },
          { label: "Flexible", value: "flexible" },
        ],
      },
      {
        id: "commitmentLevel",
        label: "On a scale of 1–10, how committed are you to improving your posture?",
        type: "slider",
        min: 1,
        max: 10,
        step: 1,
      },
    ],
  },
];

export const finalQuestion = {
  id: "additionalNotes",
  label: "Is there anything else you'd like me to know before your assessment?",
  type: "textarea" as const,
  placeholder: "Optional — anything you'd like to share...",
};
